version: '3'
services:
  my-app:
    image: itzymin/articles-products:${IMAGE_VERSION}-local
    command: ["./node_modules/.bin/nodemon", "server.js"]
    container_name: articles-products
    volumes:
      - ".:/app/:rw"
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "${EXPRESS_HOST_PORT}:${EXPRESS_CONTAINER_PORT}"
    networks:
      - my-app-network
  db:
    image: postgres:10.0-alpine
    env_file: .env
    volumes: 
      - pg-data-volume:/var/lib/postgresql/data
    ports: 
      - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
    networks:
      - my-app-network
volumes: 
  pg-data-volume:
networks:
  my-app-network: