version: '3'
services:
  my-app:
    image: itzymin/articles-products:${IMAGE_VERSION}-local
    command: ["./node_modules/.bin/nodemon", "server.js"]
    container_name: articles-products
    volumes:
      - ".:/app/:rw"
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "${PORT}:${PORT}"
    networks:
      - my-app-network

networks:
  my-app-network: